### ISSUE TITLE
java.util.NoSuchElementException error thrown when running the testgrid.sh.

### ISSUE THREAD

**Issue by kasunbg** [wso2-incubator/wso2-test-grid#91]
**Description:**
```
$> TESTGRID_HOME=/tmp/1/th JMETER_HOME=/tmp/jmeter java -jar /tmp/1/WSO2-TestGrid-0.9.0-SNAPSHOT/test-grid-0.9.0-SNAPSHOT.jar https://github.com/sameerawickramasekara/test-grid-is-resources.git wso2is 5.4.0

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.wso2.carbon.testgrid.core.TestGridMgtServiceImpl.addProductTestPlan(TestGridMgtServiceImpl.java:141)
	at org.wso2.carbon.testgrid.core.Main.main(Main.java:48)
```

**Affected Product Version:**
0.9.0-SNAPSHOT

**Comment by kasunbg** [comment]
This error occurs if the TESTGRID_HOME does not exist.

**Comment by vidurananayakkara** [comment]
When testgrid home do not exist a descriptive exception is thrown at the start.

Closing issue since already resolved
